In [40]:

# import the package
import tensorflow as tf
from tensorflow.keras.datasets import cifar10 
import numpy as np 

In [41]:
# split the train and test set
(X_train , y_train) , (X_test , y_test) = cifar10.load_data()

In [42]:
X_train.shape 

(50000, 32, 32, 3)

In [43]:
y_train[:5] # it a two dimension array but 
# we want only index of classes value like
#  6 is frog etc so reshape it

array([[6],
       [9],
       [9],
       [4],
       [1]], dtype=uint8)

In [44]:

classes = ["airplane", "automobile" , "bird" , "cat" , "deer" , "dog" , "frog" , "horse" , "ship" , "truck"]

In [45]:

# Normalize the data
X_train = X_train / 255
X_test = X_test / 255

In [46]:

# Build a model
from tensorflow.keras.layers import Conv2D , MaxPooling2D , Flatten , Dense , Dropout
from tensorflow.keras.models import Sequential

model = Sequential([
    Conv2D(32 , (3,3) , activation="relu" ,input_shape = (32,32,3)),
    MaxPooling2D(pool_size= (2,2)),

    Conv2D(64 , (3,3) , activation="relu"),
    MaxPooling2D(pool_size= (2,2)),

    Conv2D(64 , (3,3) , activation="relu"),
    MaxPooling2D(pool_size= (2,2)),

    Flatten(),
    Dense(64 , activation="relu"),
    Dense(10  ,activation="softmax")
])

In [47]:

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 30, 30, 32)        896       
                                                                 
 max_pooling2d_6 (MaxPooling  (None, 15, 15, 32)       0         
 2D)                                                             
                                                                 
 conv2d_7 (Conv2D)           (None, 13, 13, 64)        18496     
                                                                 
 max_pooling2d_7 (MaxPooling  (None, 6, 6, 64)         0         
 2D)                                                             
                                                                 
 conv2d_8 (Conv2D)           (None, 4, 4, 64)          36928     
                                                                 
 max_pooling2d_8 (MaxPooling  (None, 2, 2, 64)        

In [48]:

# compile the model
model.compile(optimizer="adam" , loss="sparse_categorical_crossentropy" , metrics=["accuracy"])

In [49]:
# train the model
model.fit(X_train , y_train , epochs=10 , validation_data=(X_test , y_test))



Epoch 1/10
1563/1563 [==============================] - 11s 6ms/step - loss: 1.5609 - accuracy: 0.4287 - val_loss: 1.2920 - val_accuracy: 0.5360
Epoch 2/10
1563/1563 [==============================] - 8s 5ms/step - loss: 1.1929 - accuracy: 0.5761 - val_loss: 1.1059 - val_accuracy: 0.6085
Epoch 3/10
1563/1563 [==============================] - 7s 5ms/step - loss: 1.0436 - accuracy: 0.6342 - val_loss: 1.0480 - val_accuracy: 0.6295
Epoch 4/10
1563/1563 [==============================] - 9s 6ms/step - loss: 0.9468 - accuracy: 0.6697 - val_loss: 1.0618 - val_accuracy: 0.6308
Epoch 5/10
1563/1563 [==============================] - 9s 6ms/step - loss: 0.8844 - accuracy: 0.6921 - val_loss: 0.9441 - val_accuracy: 0.6707
Epoch 6/10
1563/1563 [==============================] - 7s 5ms/step - loss: 0.8276 - accuracy: 0.7115 - val_loss: 0.9115 - val_accuracy: 0.6865
Epoch 7/10
1563/1563 [==============================] - 8s 5ms/step - loss: 0.7809 - accuracy: 0.7301 - val_loss: 0.9407 - val_accuracy

In [50]:

model.evaluate(X_test , y_test)

313/313 [==============================] - 1s 4ms/step - loss: 0.8697 - accuracy: 0.7094


[0.8697437644004822, 0.7093999981880188]

In [51]:

y_pred = model.predict(X_test)
y_pred[:4]

313/313 [==============================] - 1s 2ms/step


array([[1.6189998e-03, 3.2988919e-05, 1.2649228e-02, 7.0196658e-01,
        2.1114156e-03, 2.3777933e-01, 2.3393942e-02, 1.2672107e-03,
        1.9074552e-02, 1.0567816e-04],
       [1.4702185e-02, 4.8964936e-01, 2.9897083e-05, 9.8984865e-06,
        2.7415897e-06, 1.6297580e-06, 1.0092397e-07, 4.1200469e-06,
        4.7574833e-01, 1.9851774e-02],
       [2.5236813e-02, 3.3427238e-02, 1.4749730e-03, 2.7353759e-03,
        1.6028130e-03, 1.4754247e-03, 2.5604412e-04, 3.4182594e-04,
        9.1785806e-01, 1.5591448e-02],
       [8.6086214e-01, 4.1606086e-03, 8.5631562e-03, 1.7835613e-03,
        1.8565286e-03, 9.2343886e-05, 1.5127848e-04, 2.9571835e-04,
        1.2095459e-01, 1.2801334e-03]], dtype=float32)

In [52]:

y_classes = [np.argmax(element) for element in y_pred]
y_classes[:5]

[3, 1, 8, 0, 6]

In [53]:
y_test = y_test.reshape(-1,)
y_test[:5]

array([3, 8, 8, 0, 6], dtype=uint8)

In [54]:

# save the model

model.save("my_model.h5")